#!/bin/bash

FORMAT='+%Y-%m-%d'
FILE="processed"
DIETFILE="diet"

if [ "$#" -eq 0 ]; then
    rangeFrom=`date --d "-31 days" $FORMAT`
    rangeTo=`date --d "+1 day" $FORMAT`
elif [ "$#" -eq 2 ]; then
    rangeFrom=`date --d "$1 - 1 day" $FORMAT`
    rangeTo=`date --d "$2 + 1 day" $FORMAT`
else
    echo "Usage: $0 [FROM_DATE TO_DATE]"
    exit -1
fi

if [ -e "$DIETFILE" ]; then
    PLOT_DIET="\"$DIETFILE\" using 1:2 with lines dashtype 2 linecolor \"dark-yellow\" linewidth 1.5 notitle"
fi

gnuplot -p << EOF
set xdata time
set timefmt "%Y-%m-%d"
set format x "%d.%m"
set xtics 86400 # 1 day
unset mxtics
set grid
set xrange ["$rangeFrom":"$rangeTo"]
set autoscale y
set terminal x11 size 1600,1000 background "white"

plot "$FILE" using 1:3 with lines linecolor "red" linewidth 1.5 title "Trend", \
"$FILE" using 1:2 with points pointtype 6 title "Weight", \
"$FILE" using 1:3:(0):(\$2-\$3) with vectors linecolor "dark-green" linewidth 1.5 notitle, \
$PLOT_DIET
EOF
